// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_boilerplate/test/features/post/presentation/cubit/post_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_boilerplate_core/flutter_boilerplate_core.dart' as _i5;
import 'package:flutter_boilerplate_domain/feature_post/entities/post_entity.dart'
    as _i4;
import 'package:flutter_boilerplate_domain/feature_post/usecases/create_post_usecase.dart'
    as _i6;
import 'package:flutter_boilerplate_domain/feature_post/usecases/delete_post_usecase.dart'
    as _i9;
import 'package:flutter_boilerplate_domain/feature_post/usecases/get_posts_usecase.dart'
    as _i2;
import 'package:flutter_boilerplate_domain/feature_post/usecases/patch_post_usecase.dart'
    as _i8;
import 'package:flutter_boilerplate_domain/feature_post/usecases/update_post_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPostsUseCase extends _i1.Mock implements _i2.GetPostsUseCase {
  MockGetPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(List<_i4.PostEntity>?, _i5.AppFailure?)> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<(List<_i4.PostEntity>?, _i5.AppFailure?)>.value((
                  null,
                  null,
                )),
          )
          as _i3.Future<(List<_i4.PostEntity>?, _i5.AppFailure?)>);
}

/// A class which mocks [CreatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreatePostUseCase extends _i1.Mock implements _i6.CreatePostUseCase {
  MockCreatePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)> call(_i4.PostEntity? post) =>
      (super.noSuchMethod(
            Invocation.method(#call, [post]),
            returnValue: _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)>);
}

/// A class which mocks [UpdatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePostUseCase extends _i1.Mock implements _i7.UpdatePostUseCase {
  MockUpdatePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)> call(_i4.PostEntity? post) =>
      (super.noSuchMethod(
            Invocation.method(#call, [post]),
            returnValue: _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)>);
}

/// A class which mocks [PatchPostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatchPostUseCase extends _i1.Mock implements _i8.PatchPostUseCase {
  MockPatchPostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)> call(
    int? id, {
    String? title,
    String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id], {#title: title, #body: body}),
            returnValue: _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.PostEntity?, _i5.AppFailure?)>);
}

/// A class which mocks [DeletePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeletePostUseCase extends _i1.Mock implements _i9.DeletePostUseCase {
  MockDeletePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(void, _i5.AppFailure?)> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<(void, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(void, _i5.AppFailure?)>);
}
