name: flutter_boilerplate_domain
description: Domain entities, repositories, and usecases for Flutter boilerplate features.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_boilerplate_core:
    path: ../core
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  injectable: ^2.5.0
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
