name: flutter_boilerplate_core
description: Core utilities, failures, extensions, theme, and constants for Flutter boilerplate.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  logger: ^1.4.0
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0

  # Networking
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
