// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_boilerplate/test/features/post/data/repositories/post_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_boilerplate_data/feature_post/datasources/post_remote_datasource.dart'
    as _i3;
import 'package:flutter_boilerplate_data/feature_post/models/post_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostModel_0 extends _i1.SmartFake implements _i2.PostModel {
  _FakePostModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDatasource extends _i1.Mock
    implements _i3.PostRemoteDatasource {
  MockPostRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PostModel>> getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue: _i4.Future<List<_i2.PostModel>>.value(
              <_i2.PostModel>[],
            ),
          )
          as _i4.Future<List<_i2.PostModel>>);

  @override
  _i4.Future<_i2.PostModel> getPost(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue: _i4.Future<_i2.PostModel>.value(
              _FakePostModel_0(this, Invocation.method(#getPost, [id])),
            ),
          )
          as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<_i2.PostModel> createPost(_i2.PostModel? post) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [post]),
            returnValue: _i4.Future<_i2.PostModel>.value(
              _FakePostModel_0(this, Invocation.method(#createPost, [post])),
            ),
          )
          as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<_i2.PostModel> updatePost(int? id, _i2.PostModel? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [id, post]),
            returnValue: _i4.Future<_i2.PostModel>.value(
              _FakePostModel_0(
                this,
                Invocation.method(#updatePost, [id, post]),
              ),
            ),
          )
          as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<_i2.PostModel> patchPost(int? id, Map<String, dynamic>? changes) =>
      (super.noSuchMethod(
            Invocation.method(#patchPost, [id, changes]),
            returnValue: _i4.Future<_i2.PostModel>.value(
              _FakePostModel_0(
                this,
                Invocation.method(#patchPost, [id, changes]),
              ),
            ),
          )
          as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<void> deletePost(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
